/**
 * Build and download a Workspace ZIP per build brief §8.1 / plan §6.3.
 *
 * Contents:
 *   - schema.json                — combined @graph
 *   - schema-individual/*.json   — one file per entity
 *   - inline-snippet.html        — <script type="application/ld+json"> block
 *   - canonical-references.json  — flat map "@type" → schema.org URL
 *   - validation-report.txt      — current validator output at export time
 *   - README.md                  — placement instructions + agency footer
 */

import JSZip from 'jszip';
import { buildJsonLd } from '@/lib/jsonld-build';
import { validateFormState } from '@/lib/jsonld-validate';
import { entitySlugFor, urnFor, publicUrlFor } from '@/lib/id-resolver';
import { requiredFor, recommendedFor } from '@/lib/google-rich-results';
import { bareName } from '@/lib/utils';
import type { Bundle } from '@/lib/workspace-store';

export interface ExportOptions {
  /** Footer credit line (set in BundleSettings). */
  agencyCredit?: string;
}

export async function buildBundleZip(bundle: Bundle, opts: ExportOptions = {}): Promise<Blob> {
  const zip = new JSZip();
  const entities = bundle.entities;
  const idForEntity = new Map<string, string>();
  for (const e of entities) {
    idForEntity.set(e.id, publicUrlFor(bundle, e));
  }

  // 1. schema.json — combined @graph
  const graphNodes = entities.map((e) => {
    const node = buildJsonLd({ ...e.state, rootId: idForEntity.get(e.id) });
    // schema.json members shouldn't repeat @context inside @graph
    const { '@context': _ctx, ...rest } = node;
    void _ctx;
    return rest as Record<string, unknown>;
  });
  const combined = {
    '@context': 'https://schema.org',
    '@graph': graphNodes,
  };
  zip.file('schema.json', JSON.stringify(combined, null, 2) + '\n');

  // 2. schema-individual/<slug>.json
  const indiv = zip.folder('schema-individual');
  if (indiv) {
    for (const e of entities) {
      const node = buildJsonLd({ ...e.state, rootId: idForEntity.get(e.id) });
      indiv.file(`${entitySlugFor(e)}.json`, JSON.stringify(node, null, 2) + '\n');
    }
  }

  // 3. inline-snippet.html
  const refUrls = collectCanonicalRefs(entities.map((e) => e.state.rootTypeId));
  const refComment =
    refUrls.length > 0
      ? `\n${refUrls.map((u) => `   ${u}`).join('\n')}\n`
      : ' (no schema.org references)';
  const inlineHtml = `<!--
  Schema markup for ${bundle.name}.
  Generated by schema-tool on ${new Date().toISOString()}.
  Schema.org references:${refComment}
-->
<script type="application/ld+json">
${JSON.stringify(combined, null, 2)}
</script>
`;
  zip.file('inline-snippet.html', inlineHtml);

  // 4. canonical-references.json
  const refMap: Record<string, string> = {};
  for (const e of entities) {
    refMap[bareName(e.state.rootTypeId)] = `https://schema.org/${bareName(e.state.rootTypeId)}`;
  }
  zip.file('canonical-references.json', JSON.stringify(refMap, null, 2) + '\n');

  // 5. validation-report.txt
  const reportLines: string[] = [];
  reportLines.push(`schema-tool validation report — bundle "${bundle.name}"`);
  reportLines.push(`Generated: ${new Date().toISOString()}`);
  reportLines.push(`Entities : ${entities.length}`);
  reportLines.push('');
  for (const e of entities) {
    const reqs = requiredFor(e.state.rootTypeId);
    const recs = recommendedFor(e.state.rootTypeId);
    const issues = validateFormState(e.state, { requiredProps: reqs, recommendedProps: recs });
    const errs = issues.filter((i) => i.severity === 'error').length;
    const warns = issues.filter((i) => i.severity === 'warning').length;
    reportLines.push(`[${bareName(e.state.rootTypeId)}] ${entitySlugFor(e)}`);
    reportLines.push(`  errors  : ${errs}`);
    reportLines.push(`  warnings: ${warns}`);
    if (issues.length > 0) {
      for (const iss of issues) {
        reportLines.push(`  - ${iss.severity.toUpperCase()} ${iss.propertyName}: ${iss.message}`);
      }
    }
    reportLines.push('');
  }
  zip.file('validation-report.txt', reportLines.join('\n'));

  // 6. README.md
  const urns = entities.map((e) => ({
    type: bareName(e.state.rootTypeId),
    slug: entitySlugFor(e),
    urn: urnFor(bundle, e),
    publicId: publicUrlFor(bundle, e),
  }));
  const readme = `# ${bundle.name}

Schema markup bundle generated by **schema-tool** on ${new Date().toISOString()}.

## Files

- \`schema.json\` — combined \`@graph\` for all ${entities.length} entit${entities.length === 1 ? 'y' : 'ies'}.
- \`schema-individual/*.json\` — one JSON-LD file per entity.
- \`inline-snippet.html\` — paste this entire block into the \`<head>\` of the page (keeps the leading HTML comment that lists the schema.org references for editor reference).
- \`canonical-references.json\` — flat \`@type → schema.org URL\` map.
- \`validation-report.txt\` — output of the in-app validator at export time.

## Where to put it

Pick one of these strategies. Pick the same one across pages in a campaign.

1. **Inline in HTML head** — paste \`inline-snippet.html\` into the page's \`<head>\`. Easiest for one-off pages and CMSes that allow custom \`<script>\` blocks.
2. **Server-rendered template** — render \`schema.json\` from your CMS template per page. Strip the \`@graph\` if you only need a single entity per page.
3. **Tag manager** — add a custom HTML tag with the contents of \`inline-snippet.html\`. Make sure it fires on page load.

## Validation

Test the output before launch with both validators — they sometimes disagree:

- Google Rich Results Test → https://search.google.com/test/rich-results
- Schema.org validator → https://validator.schema.org/

## Cross-entity \`@id\` references

This bundle's entities use these \`@id\`s:

${urns.map((u) => `- \`${u.publicId}\` — ${u.type} (\`${u.slug}\`)`).join('\n') || '_(no entities yet)_'}

If you set Bundle → Production URL prefix before exporting, the \`@id\`s
above use that prefix. Otherwise they use the \`urn:schema-tool:\` scheme,
which is valid JSON-LD but not crawlable — set the production prefix before
shipping to production.

## Editorial / MLR review

This tool generates the markup; **it does not review your copy**. Run the
content through your usual editorial / medical-legal / regulatory pipeline
before publishing.

${opts.agencyCredit ? `\n---\n_Generated for ${opts.agencyCredit}._\n` : ''}
`;
  zip.file('README.md', readme);

  return zip.generateAsync({ type: 'blob' });
}

function collectCanonicalRefs(typeIds: readonly string[]): string[] {
  const seen = new Set<string>();
  for (const id of typeIds) seen.add(`https://schema.org/${bareName(id)}`);
  return Array.from(seen).sort();
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  setTimeout(() => {
    URL.revokeObjectURL(url);
    a.remove();
  }, 0);
}
