/**
 * Normalized model for the schema.org vocabulary subset this app ships.
 *
 * Source of truth: schema.org JSON-LD dump, filtered to:
 *   - everything in the health-lifesci extension layer
 *   - the 19 health-relevant core types named in the build brief
 *   - meta ancestors required to keep type-inheritance breadcrumbs valid
 *
 * Generated by `pnpm ingest`. Do not hand-edit `src/data/schema.generated.ts`.
 */

export type TermKind = 'Type' | 'Property' | 'Enumeration' | 'EnumerationMember';

export type ExtensionLayer =
  | 'health-lifesci'
  | 'core'
  | 'meta'
  | 'pending';

export type TermSource =
  | 'health-lifesci'
  | 'core-allowlist'
  | 'meta-ancestor';

export interface SchemaTermBase {
  /** Short prefixed form, e.g. "schema:Hospital". Primary key in this dataset. */
  id: string;
  /** Canonical schema.org URL, e.g. "https://schema.org/Hospital". */
  iri: string;
  /** rdfs:label */
  name: string;
  /** rdfs:comment, plain text (HTML stripped). */
  description: string;
  /** Original HTML if any markup matters in the UI. Optional. */
  descriptionHtml?: string;
  kind: TermKind;
  layer: ExtensionLayer;
  source: TermSource;
  /** True when the term lives on https://pending.schema.org. */
  pending: boolean;
  /** id of replacement term, if this term is deprecated. */
  supersededBy?: string;
}

export interface SchemaType extends SchemaTermBase {
  kind: 'Type' | 'Enumeration';
  /** Direct rdfs:subClassOf, normalized to id[]. */
  parents: string[];
  /** Transitive closure of parents, root → self. */
  ancestors: string[];
  /** Inverse of parents, computed at ingest time. */
  children: string[];
  /** Properties whose domainIncludes contains this type. */
  directProperties: string[];
  /** Properties inherited from ancestors, deduped. */
  inheritedProperties: string[];
  /** Only present when kind === 'Enumeration'. */
  enumerationMembers?: string[];
  /** Editorial categories assigned in src/data/categories.ts. Multi-category allowed. */
  categoryIds: string[];
}

export interface SchemaProperty extends SchemaTermBase {
  kind: 'Property';
  domainIncludes: string[];
  rangeIncludes: string[];
  subPropertyOf?: string;
  /** Optional annotation from src/data/google-rich-results.json. */
  googleRichResultStatus?: 'required' | 'recommended';
}

export interface SchemaEnumerationMember extends SchemaTermBase {
  kind: 'EnumerationMember';
  /** id of the enumeration class this member belongs to. */
  enumerationId: string;
}

export type SchemaTerm = SchemaType | SchemaProperty | SchemaEnumerationMember;

export interface SchemaDataset {
  /** schema.org version, e.g. "30.0". */
  version: string;
  /** ISO-8601 timestamp of generation. */
  generatedAt: string;
  /** The exact URL the dump was fetched from. */
  sourceUrl: string;
  /** sha256 of the raw dump file. */
  sourceHash: string;
  termsById: Record<string, SchemaTerm>;
  byKind: Record<TermKind, string[]>;
  /** categoryId → termIds. */
  categoryAssignments: Record<string, string[]>;
}

/* Type guards — used liberally in UI to narrow the discriminated union. */

export function isType(term: SchemaTerm): term is SchemaType {
  return term.kind === 'Type' || term.kind === 'Enumeration';
}

export function isProperty(term: SchemaTerm): term is SchemaProperty {
  return term.kind === 'Property';
}

export function isEnumerationMember(
  term: SchemaTerm,
): term is SchemaEnumerationMember {
  return term.kind === 'EnumerationMember';
}
